name: Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Build Package extension
        run: vsce package

      - name: Get version from package.json
        id: version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Publish Extension
        run: vsce publish ${{ steps.version.outputs.VERSION }} -p ${{ secrets.VSCE_TOKEN }}
